name: lep_monitoring
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - alsa-lib=1.2.15.3
  - altair=6.0.0
  - aom=3.9.1
  - asttokens=3.0.1
  - attr=2.5.2
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - backports.zstd=1.3.0
  - blinker=1.9.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cachetools=6.2.5
  - cairo=1.18.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.2
  - cpython=3.10.19
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.19
  - decorator=5.2.1
  - double-conversion=3.4.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - ffmpeg=8.0.1
  - filelock=3.20.3
  - fmt=12.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freeglut=3.2.2
  - freetype=2.14.1
  - fribidi=1.0.16
  - fsspec=2026.1.0
  - gdk-pixbuf=2.44.4
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.46
  - glog=0.7.1
  - glslang=16.1.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.3.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - imath=3.2.2
  - importlib-metadata=8.7.0
  - intel-gmmlib=22.9.0
  - intel-media-driver=25.3.4
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jasper=4.2.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.18
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - level-zero=1.27.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarrow=23.0.0
  - libarrow-acero=23.0.0
  - libarrow-compute=23.0.0
  - libarrow-dataset=23.0.0
  - libarrow-substrait=23.0.0
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.8
  - libclang13=21.1.8
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.18.0
  - libde265=1.0.15
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libheif=1.19.7
  - libhwloc=2.12.2
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libllvm21=21.1.8
  - liblzma=5.8.2
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopencv=4.12.0
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libopenvino=2025.4.1
  - libopenvino-auto-batch-plugin=2025.4.1
  - libopenvino-auto-plugin=2025.4.1
  - libopenvino-hetero-plugin=2025.4.1
  - libopenvino-intel-cpu-plugin=2025.4.1
  - libopenvino-intel-gpu-plugin=2025.4.1
  - libopenvino-intel-npu-plugin=2025.4.1
  - libopenvino-ir-frontend=2025.4.1
  - libopenvino-onnx-frontend=2025.4.1
  - libopenvino-paddle-frontend=2025.4.1
  - libopenvino-pytorch-frontend=2025.4.1
  - libopenvino-tensorflow-frontend=2025.4.1
  - libopenvino-tensorflow-lite-frontend=2025.4.1
  - libopus=1.6.1
  - libparquet=23.0.0
  - libpciaccess=0.18
  - libpng=1.6.54
  - libpq=18.1
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libtorch=2.9.1
  - libudev1=258.3
  - libunwind=1.8.3
  - liburing=2.13
  - libusb=1.0.29
  - libutf8proc=2.11.3
  - libuuid=2.41.3
  - libuv=1.51.0
  - libva=2.23.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.15.2
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mkl=2025.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - munkres=1.1.4
  - narwhals=2.15.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - opencv=4.12.0
  - openexr=3.4.4
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openjph=0.26.0
  - openldap=2.6.10
  - openssl=3.6.0
  - optree=0.18.0
  - orc=2.2.2
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.56.4
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.47
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.1.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - polars=1.37.1
  - polars-runtime-32=1.37.1
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.52
  - protobuf=6.31.1
  - psutil=7.2.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - py-opencv=4.12.0
  - pyarrow=23.0.0
  - pyarrow-core=23.0.0
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - pydeck=0.9.1
  - pygments=2.19.2
  - pyparsing=3.3.2
  - pyside6=6.10.1
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-gil=3.10.19
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytorch=2.9.1
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.10.1
  - rav1e=0.7.1
  - re2=2025.11.05
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rpds-py=0.30.0
  - s2n=1.6.2
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - sdl2=2.32.56
  - sdl3=3.2.30
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.10.1
  - shaderc=2025.5
  - six=1.17.0
  - sleef=3.9.0
  - smmap=5.0.2
  - snappy=1.2.2
  - spirv-tools=2025.4
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - streamlit=1.53.1
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - tenacity=9.1.2
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - toml=0.10.2
  - torchvision=0.24.1
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ultralytics=8.4.7
  - unicodedata2=17.0.0
  - urllib3=2.6.3
  - watchdog=6.0.0
  - wayland=1.24.0
  - wayland-protocols=1.47
  - wcwidth=0.2.14
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
    - Django==5.2.10
    - asgiref==3.11.0
    - sqlparse==0.5.5

prefix: "/home/stasevich/miniforge3/envs/lep_monitoring"
